### ISSUE TITLE
`npm test` throws error for missing dotenv

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#141]
Even though we don't have any tests right now, we should handle this more gracefully. 

```
~/Documents/Origin/demo-dapp$ npm test

> origin-demo-dapp@0.3.0 test /Users/stan/Documents/Origin/demo-dapp
> node scripts/test.js --env=jsdom

module.js:529
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/stan/Documents/Origin/demo-dapp/scripts/test.js:8:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by digidigo** [comment]
I can grab this one.  I don't have github access at this point though, so I'll work from a fork.
